workspace:
  base: /drone/src
  path: /usr/local/src/github.com/qnib/go-fisherman

pipeline:
  alpine:
    image: qnib/alplain-golang
    commands:
      - govendor fetch +m
      - govendor build -o go-fisherman_Alpine
  x86:
      image: qnib/uplain-golang
      commands:
        - govendor fetch +m
        - govendor build -o go-fisherman_x86
