version: "3"
services:
  http:
    image: qnib/plain-httpcheck:local12345
    ports:
     - 8080:8080
    environment:
       DELAY: "30"
       SWARM_SERVICE_NAME: "http"
    deploy:
      replicas: 3
  fisherman:
    image: qnib/uplain-golang
    environment:
       SKIP_ENTRYPOINTS: "1"
    volumes:
       - ${GOPATH}/src/github.com/qnib/go-fisherman:/usr/local/src/github.com/qnib/go-fisherman
    command: wait.sh
